#!/bin/sh
uci set luci.main.lang=zh_cn
uci set system.@system[0].hostname=LunaticUrey
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci set fstab.@global[0].anon_mount=1
uci set wireless.@wifi-device[0].disabled=0
uci set wireless.@wifi-device[1].disabled=0
uci set wireless.radio0.country='CN'
uci set dropbear.@dropbear[0].Interface='lan'
uci set wireless.@wifi-iface[0].ssid=Lunatic_$(cat /sys/class/ieee80211/phy0/macaddress | sed 's/.[0-9A-Fa-f]:.[0-9A-Fa-f]:.[0-9A-Fa-f]:\(.[0-9A-Fa-f]\):\(.[0-9A-Fa-f]\):\(.[0-9A-Fa-f]\)/\1\2\3/g' | tr :[a-z] :[A-Z])
uci set network.lan.ipaddr=192.168.9.1
uci commit

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='2U4U'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='Openwrt'" >> /etc/openwrt_release
#sed -i '/ath9k/d' /etc/modules.d/ath9k
#echo "ath9k debug=0x00000200" >> /etc/modules.d/ath9k
sed -i '202,207d' /www/luci-static/material/js/script.js

exit 0



